version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: npm install
      - run:
          name: run textlint if markdown changed
          environment:
            REVIEWDOG_VERSION: "0.9.8"
          command: |
            cond="git diff --name-only --diff-filter=ACMR origin/master | grep -a '.*.md$'"
            if eval $cond >/dev/null; then
              if ! eval $cond | xargs $(npm bin)/textlint -f pretty-error; then
                mkdir -p ~/bin/ && export PATH="~/bin/:$PATH"
                curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o ~/bin/reviewdog && chmod +x ~/bin/reviewdog
                git diff --name-only --diff-filter=ACMR origin/master | grep -a '.*.md$' \
                  | xargs $(npm bin)/textlint -f checkstyle \
                  | reviewdog -f=checkstyle -name="textlint" -ci="circle-ci"
              fi
            fi
