name: upload algolia index

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: '0.69.2'

      - name: Build
        run: hugo --minify

      - name: Use Node.js
        uses: actions/setup-node@v2.3.0
        with:
          node-version: 12.x

      - name: npm install
        run: |
          npm install

      - name: upload index to algoli
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID}}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          ALGOLIA_INDEX_NAME: "til"
          ALGOLIA_INDEX_FILE: "./public/algolia.json"
        run: |
          npm run algolia
