name: Lint Code Base

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: Lint Code Base
        uses: docker://github/super-linter:v4.8.7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false
