name: reviewdog

on: [pull_request]

jobs:
  textlint:
    name: runner / textlint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          submodules: true
      - name: textlint-github-pr-check
        uses: tsuyoshicho/action-textlint@v3.9
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          textlint_flags: "content/**/*.md"
      - name: textlint-github-check
        uses: tsuyoshicho/action-textlint@v3.9
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          textlint_flags: "content/**/*.md"
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3.9
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "content/**/*.md"
